### ISSUE TITLE
Duplicate result

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [algolia/jekyll-algolia-example#3]
Hi there, I was trying your example but I have problem with a situation.

url: https://linuxkafasi.org
repo: https://github.com/linuxkafasi/linuxkafasi.org

I am using Jekyll/Minima too, but I didn't figure it out. What I did, I got duplicate article. However, in your example it works perfect. I ended up with copy paste whole code, but still same, so how should I integrate it with Minima?

**Comment by pixelastic** [comment]
Hello,

Thanks for the bug report. I had a look at your repo and it's true that the behavior is strange. I'm not completely sure why the first record is displayed twice.

But what I found is that your `index.md` is also indexed, and because it is empty it seems to be generating an error (the display is trying to read a value of its key that is not here).

![image](https://user-images.githubusercontent.com/283419/40005048-6241649c-5797-11e8-9a8b-0a3c0e57a85e.png)
![image](https://user-images.githubusercontent.com/283419/40005073-6ef264e8-5797-11e8-9407-630807d88a95.png)

I think that if you excluding this file from the files to index, it should stop the error. You can use the `files_to_exclude` like this:

```yml
algolia:
  files_to_exclude:
    - index.md
    - about.md
    - contact.md
```


Let me know if it works better :)

**Comment by BerkhanBerkdemir** [comment]
Wow, it works like magic. Thank you!
